name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ' 8.0'
    - uses: actions/checkout@v4
    - name: Create Database
      run: |
        mkdir -p database
        touch DB/jukebox.sql
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sql dump
        DB_DATABASE: DB/jukebox.sql
      run: php artisan test
